/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as DashboardRouteImport } from './routes/Dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as FleetIndexImport } from './routes/Fleet/index'
import { Route as DashboardIndexImport } from './routes/Dashboard/index'
import { Route as ConfigureIndexImport } from './routes/Configure/index'
import { Route as LayoutRobotImport } from './routes/_layout.Robot'
import { Route as FleetAddRobotImport } from './routes/Fleet/addRobot'
import { Route as DashboardUserIndexImport } from './routes/Dashboard/user/index'
import { Route as DashboardBatteryIndexImport } from './routes/Dashboard/battery/index'
import { Route as DashboardStationIndexImport } from './routes/Dashboard/Station/index'
import { Route as DashboardRobotIndexImport } from './routes/Dashboard/Robot/index'
import { Route as DashboardFilterComponentRobotFilterImport } from './routes/Dashboard/FilterComponent/robotFilter'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FleetIndexRoute = FleetIndexImport.update({
  id: '/Fleet/',
  path: '/Fleet/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const ConfigureIndexRoute = ConfigureIndexImport.update({
  id: '/Configure/',
  path: '/Configure/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRobotRoute = LayoutRobotImport.update({
  id: '/Robot',
  path: '/Robot',
  getParentRoute: () => LayoutRoute,
} as any)

const FleetAddRobotRoute = FleetAddRobotImport.update({
  id: '/Fleet/addRobot',
  path: '/Fleet/addRobot',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUserIndexRoute = DashboardUserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardBatteryIndexRoute = DashboardBatteryIndexImport.update({
  id: '/battery/',
  path: '/battery/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardStationIndexRoute = DashboardStationIndexImport.update({
  id: '/Station/',
  path: '/Station/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardRobotIndexRoute = DashboardRobotIndexImport.update({
  id: '/Robot/',
  path: '/Robot/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardFilterComponentRobotFilterRoute =
  DashboardFilterComponentRobotFilterImport.update({
    id: '/FilterComponent/robotFilter',
    path: '/FilterComponent/robotFilter',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/Fleet/addRobot': {
      id: '/Fleet/addRobot'
      path: '/Fleet/addRobot'
      fullPath: '/Fleet/addRobot'
      preLoaderRoute: typeof FleetAddRobotImport
      parentRoute: typeof rootRoute
    }
    '/_layout/Robot': {
      id: '/_layout/Robot'
      path: '/Robot'
      fullPath: '/Robot'
      preLoaderRoute: typeof LayoutRobotImport
      parentRoute: typeof LayoutImport
    }
    '/Configure/': {
      id: '/Configure/'
      path: '/Configure'
      fullPath: '/Configure'
      preLoaderRoute: typeof ConfigureIndexImport
      parentRoute: typeof rootRoute
    }
    '/Dashboard/': {
      id: '/Dashboard/'
      path: '/'
      fullPath: '/Dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/Fleet/': {
      id: '/Fleet/'
      path: '/Fleet'
      fullPath: '/Fleet'
      preLoaderRoute: typeof FleetIndexImport
      parentRoute: typeof rootRoute
    }
    '/Dashboard/FilterComponent/robotFilter': {
      id: '/Dashboard/FilterComponent/robotFilter'
      path: '/FilterComponent/robotFilter'
      fullPath: '/Dashboard/FilterComponent/robotFilter'
      preLoaderRoute: typeof DashboardFilterComponentRobotFilterImport
      parentRoute: typeof DashboardRouteImport
    }
    '/Dashboard/Robot/': {
      id: '/Dashboard/Robot/'
      path: '/Robot'
      fullPath: '/Dashboard/Robot'
      preLoaderRoute: typeof DashboardRobotIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/Dashboard/Station/': {
      id: '/Dashboard/Station/'
      path: '/Station'
      fullPath: '/Dashboard/Station'
      preLoaderRoute: typeof DashboardStationIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/Dashboard/battery/': {
      id: '/Dashboard/battery/'
      path: '/battery'
      fullPath: '/Dashboard/battery'
      preLoaderRoute: typeof DashboardBatteryIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/Dashboard/user/': {
      id: '/Dashboard/user/'
      path: '/user'
      fullPath: '/Dashboard/user'
      preLoaderRoute: typeof DashboardUserIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFilterComponentRobotFilterRoute: typeof DashboardFilterComponentRobotFilterRoute
  DashboardRobotIndexRoute: typeof DashboardRobotIndexRoute
  DashboardStationIndexRoute: typeof DashboardStationIndexRoute
  DashboardBatteryIndexRoute: typeof DashboardBatteryIndexRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFilterComponentRobotFilterRoute:
    DashboardFilterComponentRobotFilterRoute,
  DashboardRobotIndexRoute: DashboardRobotIndexRoute,
  DashboardStationIndexRoute: DashboardStationIndexRoute,
  DashboardBatteryIndexRoute: DashboardBatteryIndexRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LayoutRouteChildren {
  LayoutRobotRoute: typeof LayoutRobotRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutRobotRoute: LayoutRobotRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRouteRouteWithChildren
  '': typeof LayoutRouteWithChildren
  '/Fleet/addRobot': typeof FleetAddRobotRoute
  '/Robot': typeof LayoutRobotRoute
  '/Configure': typeof ConfigureIndexRoute
  '/Dashboard/': typeof DashboardIndexRoute
  '/Fleet': typeof FleetIndexRoute
  '/Dashboard/FilterComponent/robotFilter': typeof DashboardFilterComponentRobotFilterRoute
  '/Dashboard/Robot': typeof DashboardRobotIndexRoute
  '/Dashboard/Station': typeof DashboardStationIndexRoute
  '/Dashboard/battery': typeof DashboardBatteryIndexRoute
  '/Dashboard/user': typeof DashboardUserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/Fleet/addRobot': typeof FleetAddRobotRoute
  '/Robot': typeof LayoutRobotRoute
  '/Configure': typeof ConfigureIndexRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/Fleet': typeof FleetIndexRoute
  '/Dashboard/FilterComponent/robotFilter': typeof DashboardFilterComponentRobotFilterRoute
  '/Dashboard/Robot': typeof DashboardRobotIndexRoute
  '/Dashboard/Station': typeof DashboardStationIndexRoute
  '/Dashboard/battery': typeof DashboardBatteryIndexRoute
  '/Dashboard/user': typeof DashboardUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRouteRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/Fleet/addRobot': typeof FleetAddRobotRoute
  '/_layout/Robot': typeof LayoutRobotRoute
  '/Configure/': typeof ConfigureIndexRoute
  '/Dashboard/': typeof DashboardIndexRoute
  '/Fleet/': typeof FleetIndexRoute
  '/Dashboard/FilterComponent/robotFilter': typeof DashboardFilterComponentRobotFilterRoute
  '/Dashboard/Robot/': typeof DashboardRobotIndexRoute
  '/Dashboard/Station/': typeof DashboardStationIndexRoute
  '/Dashboard/battery/': typeof DashboardBatteryIndexRoute
  '/Dashboard/user/': typeof DashboardUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Dashboard'
    | ''
    | '/Fleet/addRobot'
    | '/Robot'
    | '/Configure'
    | '/Dashboard/'
    | '/Fleet'
    | '/Dashboard/FilterComponent/robotFilter'
    | '/Dashboard/Robot'
    | '/Dashboard/Station'
    | '/Dashboard/battery'
    | '/Dashboard/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/Fleet/addRobot'
    | '/Robot'
    | '/Configure'
    | '/Dashboard'
    | '/Fleet'
    | '/Dashboard/FilterComponent/robotFilter'
    | '/Dashboard/Robot'
    | '/Dashboard/Station'
    | '/Dashboard/battery'
    | '/Dashboard/user'
  id:
    | '__root__'
    | '/'
    | '/Dashboard'
    | '/_layout'
    | '/Fleet/addRobot'
    | '/_layout/Robot'
    | '/Configure/'
    | '/Dashboard/'
    | '/Fleet/'
    | '/Dashboard/FilterComponent/robotFilter'
    | '/Dashboard/Robot/'
    | '/Dashboard/Station/'
    | '/Dashboard/battery/'
    | '/Dashboard/user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  FleetAddRobotRoute: typeof FleetAddRobotRoute
  ConfigureIndexRoute: typeof ConfigureIndexRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  FleetAddRobotRoute: FleetAddRobotRoute,
  ConfigureIndexRoute: ConfigureIndexRoute,
  FleetIndexRoute: FleetIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Dashboard",
        "/_layout",
        "/Fleet/addRobot",
        "/Configure/",
        "/Fleet/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Dashboard": {
      "filePath": "Dashboard/route.tsx",
      "children": [
        "/Dashboard/",
        "/Dashboard/FilterComponent/robotFilter",
        "/Dashboard/Robot/",
        "/Dashboard/Station/",
        "/Dashboard/battery/",
        "/Dashboard/user/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/Robot"
      ]
    },
    "/Fleet/addRobot": {
      "filePath": "Fleet/addRobot.tsx"
    },
    "/_layout/Robot": {
      "filePath": "_layout.Robot.tsx",
      "parent": "/_layout"
    },
    "/Configure/": {
      "filePath": "Configure/index.tsx"
    },
    "/Dashboard/": {
      "filePath": "Dashboard/index.tsx",
      "parent": "/Dashboard"
    },
    "/Fleet/": {
      "filePath": "Fleet/index.tsx"
    },
    "/Dashboard/FilterComponent/robotFilter": {
      "filePath": "Dashboard/FilterComponent/robotFilter.tsx",
      "parent": "/Dashboard"
    },
    "/Dashboard/Robot/": {
      "filePath": "Dashboard/Robot/index.tsx",
      "parent": "/Dashboard"
    },
    "/Dashboard/Station/": {
      "filePath": "Dashboard/Station/index.tsx",
      "parent": "/Dashboard"
    },
    "/Dashboard/battery/": {
      "filePath": "Dashboard/battery/index.tsx",
      "parent": "/Dashboard"
    },
    "/Dashboard/user/": {
      "filePath": "Dashboard/user/index.tsx",
      "parent": "/Dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
